jsonrpc:
    discovery:
        zookeeper: localhost:2181
dubbo:
    registry:
        address: zookeeper://127.0.0.1:2181

---
spring:
    application:
        name: jsonrpc-provider
    profiles: jsonrpc-provider
server:
    port: 8000
jsonrpc:
    server:
        port: 12306

---
spring:
    application:
        name: jsonrpc-consumer
    profiles: jsonrpc-consumer
server:
    port: 8001
jsonrpc:
    client:
        serverList: localhost:12306
        connectionTimeoutMS: 5000
        invokeTimeoutMS: 1000

---
spring:
    application:
        name: dubbo-provider
    profiles: dubbo-provider
server:
    port: 9000
dubbo:
    protocol:
        name: dubbo
        port: 12305
    scan:
        base-packages: com.github.xincao9.jsonrpc.benchmark.provider.dubbo

---
spring:
    application:
        name: dubbo-consumer
    profiles: dubbo-consumer
server:
    port: 9001